export const JOB_TYPES = [
  'Full Time',
  'Part Time',
  'Internship',
  'Contract',
  'Remote',
];

export const APPLICATION_STATUSES = [
  'Applied',
  'Assessment',
  'Interview',
  'Offer',
  'Rejected',
  'Withdrawn',
];

// Status badge styling definitions (accessible and clean)
export const STATUS_CONFIG = {
  Applied: {
    label: 'Applied',
    badgeClass: 'bg-blue-50 text-blue-700 border border-blue-200',
    dotClass: 'bg-blue-500',
    description: 'Application submitted and pending review',
  },
  Assessment: {
    label: 'Assessment',
    badgeClass: 'bg-amber-50 text-amber-700 border border-amber-200',
    dotClass: 'bg-amber-500',
    description: 'Technical test or take-home assignment',
  },
  Interview: {
    label: 'Interview',
    badgeClass: 'bg-purple-50 text-purple-700 border border-purple-200',
    dotClass: 'bg-purple-500',
    description: 'Screening or rounds of interviews in progress',
  },
  Offer: {
    label: 'Offer',
    badgeClass: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
    dotClass: 'bg-emerald-500',
    description: 'Job offer received! Congratulations!',
  },
  Rejected: {
    label: 'Rejected',
    badgeClass: 'bg-rose-50 text-rose-700 border border-rose-200',
    dotClass: 'bg-rose-500',
    description: 'Application not selected to move forward',
  },
  Withdrawn: {
    label: 'Withdrawn',
    badgeClass: 'bg-slate-100 text-slate-700 border border-slate-200',
    dotClass: 'bg-slate-400',
    description: 'Candidate voluntarily withdrew application',
  },
};

export const INITIAL_SAMPLE_APPLICATIONS = [
  {
    id: 'job-1',
    company: 'Stripe',
    jobTitle: 'Frontend Engineer',
    location: 'San Francisco, CA (Hybrid)',
    jobType: 'Full Time',
    applicationDate: '2026-03-01',
    applicationUrl: 'https://stripe.com/jobs/frontend-engineer',
    status: 'Interview',
    notes: 'Completed technical screen with hiring manager. System design and pair coding interview scheduled for next Thursday. Focus on React performance and component architecture.',
    createdAt: '2026-03-01T10:30:00.000Z',
    updatedAt: '2026-03-06T14:15:00.000Z',
  },
  {
    id: 'job-2',
    company: 'Linear',
    jobTitle: 'Product Designer / UI Developer',
    location: 'Remote',
    jobType: 'Remote',
    applicationDate: '2026-03-04',
    applicationUrl: 'https://linear.app/careers',
    status: 'Offer',
    notes: 'Received written offer! Base $165k + equity package. Decision deadline is March 25. Great team culture and async-first workflow.',
    createdAt: '2026-03-04T12:00:00.000Z',
    updatedAt: '2026-03-10T16:45:00.000Z',
  },
  {
    id: 'job-3',
    company: 'Datadog',
    jobTitle: 'Senior Full Stack Developer',
    location: 'New York, NY',
    jobType: 'Full Time',
    applicationDate: '2026-02-20',
    applicationUrl: 'https://careers.datadoghq.com',
    status: 'Assessment',
    notes: 'Submitted HackerRank coding assessment on algorithms and API design. Waiting for feedback from recruiter Sarah.',
    createdAt: '2026-02-20T09:15:00.000Z',
    updatedAt: '2026-02-28T11:20:00.000Z',
  },
  {
    id: 'job-4',
    company: 'Vercel',
    jobTitle: 'Developer Experience Engineer',
    location: 'Remote',
    jobType: 'Remote',
    applicationDate: '2026-03-08',
    applicationUrl: 'https://vercel.com/careers',
    status: 'Applied',
    notes: 'Applied via company portal with portfolio link and custom cover letter highlighting Next.js and open source contributions.',
    createdAt: '2026-03-08T15:20:00.000Z',
    updatedAt: '2026-03-08T15:20:00.000Z',
  },
  {
    id: 'job-5',
    company: 'Figma',
    jobTitle: 'Software Engineer - Canvas Team',
    location: 'San Francisco, CA',
    jobType: 'Full Time',
    applicationDate: '2026-02-14',
    applicationUrl: 'https://figma.com/careers',
    status: 'Rejected',
    notes: 'Reached round 2 interview. Received kind automated rejection stating high volume of applicants. Re-apply in 6 months.',
    createdAt: '2026-02-14T08:00:00.000Z',
    updatedAt: '2026-03-02T17:30:00.000Z',
  },
  {
    id: 'job-6',
    company: 'GitHub',
    jobTitle: 'Open Source Fellow / Intern',
    location: 'Remote',
    jobType: 'Internship',
    applicationDate: '2026-01-25',
    applicationUrl: 'https://github.com/about/careers',
    status: 'Withdrawn',
    notes: 'Withdrew application after accepting another timeline commitment.',
    createdAt: '2026-01-25T11:00:00.000Z',
    updatedAt: '2026-02-10T09:00:00.000Z',
  },
];
